import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useShop } from "../context/ShopContext";
import { colors, radius, spacing } from "../theme";

export default function PaymentMethodsScreen({ navigation }) {
  const { paymentMethods, addPaymentMethod, removePaymentMethod } = useShop();
  const [number, setNumber] = useState(""); const [name, setName] = useState(""); const [expiry, setExpiry] = useState(""); const [showForm, setShowForm] = useState(false);
  const add = () => { const digits = number.replace(/\D/g, ""); if (digits.length < 12 || !name.trim() || !/^\d{2}\/\d{2}$/.test(expiry)) return; addPaymentMethod({ id: `${Date.now()}`, brand: /^4/.test(digits) ? "Visa" : "Tarjeta", last4: digits.slice(-4), name: name.trim(), expiry }); setNumber(""); setName(""); setExpiry(""); setShowForm(false); };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={24} color={colors.text}/></Pressable><Text style={styles.title}>MÉTODOS DE PAGO</Text><View style={{width:24}} /></View><ScrollView contentContainerStyle={styles.content}>{paymentMethods.map(card => <View key={card.id} style={styles.card}><Ionicons name="card-outline" size={22} color={colors.accent}/><View style={{flex:1}}><Text style={styles.cardName}>{card.brand} •••• {card.last4}</Text><Text style={styles.hint}>{card.name} · vence {card.expiry}</Text></View><Pressable onPress={() => removePaymentMethod(card.id)}><Ionicons name="trash-outline" size={19} color={colors.danger}/></Pressable></View>)}{!paymentMethods.length && <Text style={styles.empty}>No tienes tarjetas guardadas.</Text>}{showForm && <View style={styles.form}><Input label="NÚMERO DE TARJETA" value={number} onChangeText={v => setNumber(v.replace(/[^\d ]/g, "").slice(0, 19))} keyboardType="number-pad" placeholder="1234 5678 9012 3456"/><Input label="NOMBRE DEL TITULAR" value={name} onChangeText={setName} placeholder="Como aparece en la tarjeta"/><Input label="VENCIMIENTO (MM/AA)" value={expiry} onChangeText={setExpiry} keyboardType="number-pad" placeholder="12/28"/><Pressable style={styles.save} onPress={add}><Text style={styles.saveText}>GUARDAR TARJETA</Text></Pressable></View>}<Pressable style={styles.add} onPress={() => setShowForm(true)}><Ionicons name="add" size={18} color="#fff"/><Text style={styles.addText}>AGREGAR TARJETA</Text></Pressable><Text style={styles.note}>Por seguridad, no guardamos CVV ni número completo.</Text></ScrollView></SafeAreaView>;
}
function Input({label,...props}) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor={colors.textFaint}/></View>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},header:{height:54,paddingHorizontal:spacing.lg,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{color:colors.text,fontWeight:"800",letterSpacing:1},content:{padding:spacing.lg,gap:12},card:{flexDirection:"row",alignItems:"center",gap:12,padding:15,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surfaceAlt},cardName:{color:colors.text,fontWeight:"700"},hint:{color:colors.textMuted,fontSize:11,marginTop:3},empty:{color:colors.textMuted,textAlign:"center",marginVertical:25},form:{gap:10,marginTop:8},label:{color:colors.textFaint,fontSize:10,fontWeight:"700",marginTop:4},input:{height:46,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,color:colors.text,paddingHorizontal:12,marginTop:5},add:{height:50,backgroundColor:colors.primary,borderRadius:radius.md,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:7,marginTop:8},addText:{color:"#fff",fontWeight:"800"},save:{height:48,backgroundColor:colors.success,borderRadius:radius.md,alignItems:"center",justifyContent:"center",marginTop:8},saveText:{color:"#fff",fontWeight:"800"},note:{color:colors.textFaint,fontSize:11,textAlign:"center",marginTop:5}});
